baseURL = "https://webcyou.github.io/crypto-currency-icon/"
languageCode = "ja"
title = "Crypto Currency Icon Show Page"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"
