baseURL = "https://webcyou.github.io/crypto-currency-icon/"
#languageCode = "ja"
languageCode = "en-us"
title = "Crypto Currency Icon"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "webcyou"
	description = "CryptoCurrency Icon CSS Style"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/webcyou/crypto-currency-icon"

	version = "0.1.7"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["css/crypto-currency-icon.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "webcyou"
	github  = "webcyou"
	email   = "info@webcyou.com"


[[menu.main]]
	name   = "Top"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Icons"
	url    = "icons/"
	weight = 20

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
